print("            ()_______()         ")
print("   _________/         \\")
print("  /            .  .    |  ")
print("  |           (  o  )  |         ")
print(" 0|                   /           ")
print("  |                   |            ")
print("   \    __________    |         ")
print("    |  | |        |  |\               ")
print("    |  | |        |  | |                ")
print("    |__|_|        |__|_|                      ")